import { Lora, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"], // Regular and Bold
  style: ["normal", "italic"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Regular, Medium, and Bold
});


export const metadata = {
  title: "RK Dairy Farm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body>
        <Header />
       <section className="">{children}</section>
        
        </body>
    </html>
  );
}
